language: generic

install:
  - curl https://leanprover.github.io/lean-nightly/build/lean-nightly-linux.tar.gz | tar xz -C ..
  - export PATH=../lean-nightly-linux/bin:$PATH

script:
  - leanpkg test
  - lean --recursive --export=mathlib.txt
  - leanchecker mathlib.txt
